config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

     resources :cars

     resources :places

     resources :events

end

app/models/car.rb
class Car < ActiveRecord::Base
	has_many :event_cars
end

app/models/event.rb
class Event < ActiveRecord::Base
   has_many :event_places
   has_many :event_cars
   has_many :places, through: :event_places
   has_many :cars, through: :event_cars
end

app/models/event_car.rb
class EventCar < ActiveRecord::Base
  belongs_to :car
  belongs_to :event
end

app/models/event_place.rb
class EventPlace < ActiveRecord::Base
  belongs_to :place
  belongs_to :event
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :event_places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(car_params)
    redirect_to cars_path
  end

def edit
  @car = Car.find(params[:id])
end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to cars_path
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:number, :model, :year, :car_kind)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @cars = Car.all
    @places = Place.all
  end

  def create
    @event = Event.create(event_params)
    @event.cars = Car.find(params[:car_ids]) if params[:car_ids]
    @event.places = Place.find(params[:place_ids]) if params[:place_ids]
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
    @cars = Car.all
    @places = Place.all
  end

  def update
    @event = Event.find(params[:id])
    @event.cars = Car.find(params[:car_ids]) if params[:car_ids]
    @event.places = Place.find(params[:place_ids]) if params[:place_ids]
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:begin_time, :end_time, :description, car_ids: [], place_ids: [])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  
  def index
  	@places = Place.all
  end

  def new
  	@place = Place.new
  end
  
  def create
    @place = Place.create(place_params)
    redirect_to places_path
  end

  def edit
  	@place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    redirect_to places_path
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:address, :city, :landmark, :latitude, :longitude)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/cars/_form.html.erb
 <%= form_for @car do |f| %>

    <div class="form-inputs">
      
      <div> 
        <%= f.label :number_of_car %><br>
        <%= f.text_field :number %>
      </div>
      
      <div>
        <%= f.label :model_of_car %><br>
        <%= f.text_field :model %>
      </div>
      
      <div>
        <%= f.label :year_of_production %><br>
        <%= f.text_field :year %>
      </div>
      
      <div>
        <%= f.label :kind_of_car %><br>
        <%= f.text_field :car_kind %>
      </div>
      
    </div>

  <div class="form-submit">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing cars</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>List of Cars</h1>

<table class="table table-striped">
  <tr>
    <th>Number of the car</th>
    <th>Model of the car</th>
    <th>Year of production</th>
    <th>Kind of the car</th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.number %></td>
    <td><%= car.model %></td>
    <td><%= car.year %></td>
    <td><%= car.car_kind %></td>

    <td><%= link_to "Edit", edit_car_path(car) %></td>
    <td><%= link_to "Destroy", car, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to "Add new car", new_car_path %>
<br>
<%= link_to 'Back to Index', root_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

  <div>
    <%= f.label :enter_time_of_begining %><br>
    <%= f.datetime_field :begin_time %>
  </div>

  <div>
    <%= f.label :enter_time_of_ending %><br>
    <%= f.datetime_field :end_time %>
  </div>

  <div>
    <%= f.label :enter_description %><br>
    <%= f.text_area :description  %>
  </div>

   <div>
    <%= f.label :select_cars_from_list %><br>
    <%= select_tag("car_ids[]", options_for_select(Car.all.collect { |car| [car.model, car.id] }, @event.cars.collect { |car| car.id}), {multiple: true, size: 6})%>
   </div>

  <div>
    <%= f.label :select_places_from_list %><br>
    <%= select_tag("place_ids[]", options_for_select(Place.all.collect { |place| [place.address, place.id] }, @event.places.collect { |place| place.id}), {multiple: true, size: 6})%>

  </div>

  <div class="form-submit">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing events</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>List of Events</h1>

<table class="table table-striped">
  <tr>
    <th>Event begins at:</th>
    <th>Event ends at:</th>
    <th>Description of event</th>
    <th>Cars in event</th>
    <th>Places of event</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.begin_time %></td>
    <td><%= event.end_time %></td>
    <td><%= event.description %></td>
    <td>
      <% event.cars.each do |с| %>
        <%= с.model %>
      <% end %>
    </td>
    <td>
      <% event.places.each do |p| %>
        <%= p.address %>
      <% end %>
    </td>

    <td><%= link_to "Edit", edit_event_path(event) %></td>
    <td><%= link_to "Destroy", event, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to "Add new event", new_event_path %>
<br>
<%= link_to 'Back to Index', root_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<h2>HomePage</h2>

<%= link_to 'List of cars', cars_path(@cars) %>
<br>
<%= link_to 'List of places', places_path(@places) %>
<br>
<%= link_to 'List of events', events_path(@events) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaPlIv</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/_form.html.erb
 <%= form_for @place do |f| %>

    <div class="form-inputs">
      
      <div> 
        <%= f.label :enter_address %><br>
        <%= f.text_field :address %>
      </div>
      
      <div>
        <%= f.label :enter_city %><br>
        <%= f.text_field :city %>
      </div>
      
      <div>
        <%= f.label :enter_latitude %><br>
        <%= f.text_field :latitude %>
      </div>
      
      <div>
        <%= f.label :enter_longitude %><br>
        <%= f.text_field :longitude %>
      </div>
      
      <div>
        <%= f.label :enter_type_of_place %><br>
        <%= f.text_field :landmark %>
      </div>

    </div>

  <div class="form-submit">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing places</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>List of Places</h1>

<table class="table table-striped">
  <tr>
    <th>Адреса</th>
    <th>Місто</th>
    <th>Kоординати: широта</th>
    <th>Kоординати: довгота</th>
    <th>Тип місця</th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.address %></td>
    <td><%= place.city %></td>
    <td><%= place.latitude %></td>
    <td><%= place.longitude %></td>
    <td><%= place.landmark %></td>

    <td><%= link_to "Edit", edit_place_path(place) %></td>
    <td><%= link_to "Destroy", place, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to "Add new place", new_place_path %>
<br>
<%= link_to 'Back to Index', root_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>